services:
  php:
    build:
      context: docker/php
      target: php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    depends_on:
      - db
      - redis
      - es
      - mail
    volumes:
      - ./src:/var/www/html

  php-debug:
    build:
      context: docker/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    depends_on:
      - db
      - redis
      - es
      - mail
    volumes:
      - ./src:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway

  node:
    image: node:18.16-buster
    entrypoint: /bin/bash
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    profiles:
      - cli

  web:
    build: docker/nginx
    depends_on:
      - php
    ports:
      - 8080:443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=magento2
      - MARIADB_USER=magento2
      - MARIADB_PASSWORD=magento2
      - MARIADB_DATABASE=magento2
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  es:
    image: elasticsearch:7.17.9
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - es-data:/usr/share/elasticsearch/data

  mq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_NODENAME: rabbit@mq
      RABBITMQ_ERLANG_COOKIE: erlang-cookie-mq
    ports:
      - 15672:15672
    volumes:
      - mq-data:/var/lib/rabbitmq

  redis:
    image: redis:7.0
    volumes:
      - redis-data:/data

  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025

  loki:
    image: grafana/loki:2.7.4
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./docker/loki/config.yml:/etc/loki/config.yml
    profiles:
      - grafana

  promtail:
    image: grafana/promtail:2.7.4
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./src/var/log:/var/log
      - ./docker/promtail/config.yml:/etc/promtail/config.yml
    depends_on:
      - loki
    profiles:
      - grafana

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - promtail
    profiles:
      - grafana
    environment:
      - GF_INSTALL_PLUGINS=redis-datastore

volumes:
  db-data:
  es-data:
  es-plugin-data:
  mq-data:
  redis-data:
  grafana-data:
