server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - multiline:
          firstline: '^\[\d{4}-\d{2}-\d{2}T\d{1,2}:\d{2}:\d{2}.*\]'
      - regex:
          expression: '^(?s)\[.*\] \w+\.(?P<level>\w+)(?P<content>.*)$'
      - labels:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
